# Generated by Django 3.0.4 on 2020-03-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200323_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlinks',
            new_name='Movielink',
        ),
    ]
