# Generated by Django 3.0.4 on 2020-03-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200323_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='casr',
            new_name='cast',
        ),
    ]
